### ISSUE TITLE
operator-config-example User Friendly Comments

### ISSUE THREAD

**Issue by wesfloyd** [NethermindEth/eigenlayer#133]
**Describe the bug**
The [current example config file](https://github.com/NethermindEth/eigenlayer/blob/develop/cli/operator/config/operator-config-example.yaml) does not explain which fields are required and/or their purpose.

The current link to delgation manager uses colons (:) instead of periods (.) in its url and as a result is unreachable. E.g.:
https://github:com/Layr-Labs/eigenlayer-contracts/blob/master/src/contracts/interfaces/IDelegationManager:sol
vs
https://github.com/Layr-Labs/eigenlayer-contracts/blob/master/src/contracts/interfaces/IDelegationManager.sol

**Expected behavior**
The example config file should be self describing so the user does not need to understand and parse solidity code in order to use (operate) the config file.

Can we please add explanations for each field including: their purpose and whether they are required or optional?

**Comment by shrimalmadhur** [comment]
Thanks @wesfloyd for feedback.

Good catch on the link. I will fix it. 

All fields are required and operators have to have all of them filled. Not sure what's the best way to show that

The reason I have linked to solidity file link is because that's the source of truth and if we copy it, they can diverge so the operator just need to read the comments from the solidity file, they don't need to understand the solidity code. Having said that I can link to the exact line number if that helps.

**Comment by shrimalmadhur** [comment]
@wesfloyd https://github.com/NethermindEth/eigenlayer/pull/134/files
